.\" Source: ./sfs.c
.\" Generated with ROBODoc Version 4\.99\.43 (Jul 15 2018)
.\" ROBODoc (c) 1994\-2015 by Frans Slothouber and many others\.
.TH file_data 3 "Nov 05, 2018" sfs "sfs Reference"

.SH NAME
struct \fBfile_data\fR \-\- file entry in the Index Area

.SH DESCRIPTION
Corresponds to the file and deleted file entries in the Index
Area\.  The blocks used by the file must follow each other\.

.SH FIELDS
num_cont \- number of continuations used by the entry
time_stamp \- time\-date of creation/modification of the file
start_block \- first block used by the file
end_block \- last block used by the file
file_len \- the size of the file in bytes
char \- absolute path, with directory names separated by '/'
