.\" Source: ./sfs.c
.\" Generated with ROBODoc Version 4\.99\.43 (Jul 15 2018)
.\" ROBODoc (c) 1994\-2015 by Frans Slothouber and many others\.
.TH free_list_add 3 "Nov 04, 2018" sfs "sfs Reference"

.SH NAME
\fBfree_list_add\fR \-\- add free block to the free list

.SH DESCRIPTION
Adds new blocks into the free list\.  If the blocks are before and/or
after existing free list entries, the entries are merged\.
Blocks can only be merged with blocks which have delfile NULL\.

.SH PARAMETERS
SFS \- the SFS structure variable
start \- the block where the new free area starts
length \- the number of blocks in the new free area

.SH RETURN VALUE
Returns 0 on success and \-1 on error\.
