.\" Source: ./sfs.c
.\" Generated with ROBODoc Version 4\.99\.43 (Mar  7 2018)
.\" ROBODoc (c) 1994\-2015 by Frans Slothouber and many others\.
.TH sfs_resize 3 "Oct 24, 2018" sfs "sfs Reference"

.SH NAME
\fBsfs_resize\fR \-\- resize a file

.SH DESCRIPTION
Resize a file *path* to size *len*\.  Truncate the file if its size
is less than *len*\.  Otherwise, fills with null characters\.

.SH PARAMETERS
SFS \- the SFS structure variable
path \- the absolute path of the file
len \- the new size for the file

.SH RETURN VALUE
Returns 0 on success and \-1 on error\.
