.\" Source: ./sfs_fuse.c
.\" Generated with ROBODoc Version 4\.99\.43 (Jul 15 2018)
.\" ROBODoc (c) 1994\-2015 by Frans Slothouber and many others\.
.TH sfs_fuse 3 "Nov 05, 2018" sfs "sfs Reference"

.SH NAME
\fBsfs_fuse\fR \-\- FUSE interface for the sfs implementation

.SH DESCRIPTION
FUSE interface implementing severatl FUSE functions\.
