.\" Source: ./sfs.c
.\" Generated with ROBODoc Version 4\.99\.43 (Jul 15 2018)
.\" ROBODoc (c) 1994\-2015 by Frans Slothouber and many others\.
.TH volume_data 3 "Nov 05, 2018" sfs "sfs Reference"

.SH NAME
struct \fBvolume_data\fR \-\- information in the volume ID entry

.SH DESCRIPTION
The last entry of the Index Area\.

.SH FIELDS
time_stamp \- time\-date of creation of the filesystem
name \- name of the volume
